spring.application.name=pedidos2026

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/novapaperDB
spring.datasource.username=postgres
<<<<<<< HEAD
<<<<<<< HEAD
spring.datasource.password=1103
=======
spring.datasource.password=12345678
>>>>>>> branch 'master' of https://github.com/MayNau22/gestion-pedidos.git
=======
spring.datasource.password=1103

>>>>>>> 8f1af7345385b1bebdda2f3b0949329c6756315e
