spring.application.name=pedidos2026

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/novapaperDB
spring.datasource.username=postgres
spring.datasource.password=Dic2201@